// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4hs8wBTbEkqxPoN8F9xDDz965lSpj7RY',
    appId: '1:990884533357:web:eddaaceddf0d480eca9b64',
    messagingSenderId: '990884533357',
    projectId: 'qlcv-test1',
    authDomain: 'qlcv-test1.firebaseapp.com',
    storageBucket: 'qlcv-test1.appspot.com',
    measurementId: 'G-VLZJ5P3S4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3czCqLTTju8EwgFXLfGUw9wo3IOAFNS0',
    appId: '1:990884533357:android:21130e57e3cb3ae5ca9b64',
    messagingSenderId: '990884533357',
    projectId: 'qlcv-test1',
    storageBucket: 'qlcv-test1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnlsXwMoTP9HcvBNeSAI2X5QhsXcXjFN4',
    appId: '1:990884533357:ios:4372be3ca5657d3bca9b64',
    messagingSenderId: '990884533357',
    projectId: 'qlcv-test1',
    storageBucket: 'qlcv-test1.appspot.com',
    iosClientId: '990884533357-rrbjq2020varo6bancorah4pqlopgcaa.apps.googleusercontent.com',
    iosBundleId: 'com.tin.qlcv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnlsXwMoTP9HcvBNeSAI2X5QhsXcXjFN4',
    appId: '1:990884533357:ios:4372be3ca5657d3bca9b64',
    messagingSenderId: '990884533357',
    projectId: 'qlcv-test1',
    storageBucket: 'qlcv-test1.appspot.com',
    iosClientId: '990884533357-rrbjq2020varo6bancorah4pqlopgcaa.apps.googleusercontent.com',
    iosBundleId: 'com.tin.qlcv',
  );
}
